### ISSUE TITLE
Can't import ext::ai reflection

### ISSUE THREAD

**Issue by anbuzin** [geldata/gel-python#706]
```python
from models.ext import ai
```

```
TypeError: cannot specify both default and default_factory
```

**Comment by elprans** [comment]
Should have been fixed in #704

**Comment by anbuzin** [comment]
Tried it with latest master, unfortunately the error is still there.

**Comment by 1st1** [comment]
I can't repro this specific error @anbuzin 

Are you sure you got

> TypeError: cannot specify both default and default_factory

with specifically this schema? Maybe `uv` is caching the package for you and you didn't get a fresh build of master?

**Comment by 1st1** [comment]
There are other errors though, so I'll try to fix them

**Comment by anbuzin** [comment]
Ok so this exact schema in a brand new project on 6.8 and

```
 + gel==3.1.0 (from git+https://github.com/geldata/gel-python.git@60800748801dd5ebac89a185785a6f99578a99e5)
```

Gives this error:

```
(orm-repro) andrey@mac orm-repro % python3 main.py
Traceback (most recent call last):
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/main.py", line 1, in <module>
    from models.ext import ai
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/models/ext/ai.py", line 10, in <module>
    from ..__variants__.ext import ai as base
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/models/__variants__/ext/ai.py", line 984, in <module>
    class Config(
    ...<164 lines>...
            pass
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/models/__variants__/ext/ai.py", line 1059, in Config
    class __variants__(cfg.ExtensionConfig.__variants__):
    ...<85 lines>...
        Any = TypeVar("Any", bound="Config | Base | Required | Partial")
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/models/__variants__/ext/ai.py", line 1140, in __variants__
    class Partial(PartialBase, cfg.ExtensionConfig.__variants__.Partial):  # type: ignore [misc, unused-ignore]
        indexer_naptime: OptionalProperty[___std_1__.duration, timedelta]
        providers: MultiLink[___ext_ai__.ProviderConfig | ___ext_ai__.ProviderConfig.__variants__.Partial]
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/gel/_internal/_qbmodel/_pydantic/_models.py", line 70, in __new__
    super().__new__(mcls, name, bases, namespace, **kwargs),
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 221, in __new__
    set_model_fields(cls, config_wrapper=config_wrapper, ns_resolver=ns_resolver)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 544, in set_model_fields
    fields, class_vars = collect_model_fields(cls, config_wrapper, ns_resolver, typevars_map=typevars_map)
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/pydantic/_internal/_fields.py", line 168, in collect_model_fields
    assigned_value = getattr(cls, ann_name, PydanticUndefined)
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/gel/_internal/_qbmodel/_abstract/_descriptors.py", line 148, in __get__
    return self.get(owner)
           ~~~~~~~~^^^^^^^
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/gel/_internal/_qbmodel/_abstract/_descriptors.py", line 119, in get
    t = self.get_resolved_type()
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/gel/_internal/_qbmodel/_abstract/_descriptors.py", line 108, in get_resolved_type
    t = self._try_resolve_type()
  File "/Users/andrey/local/projects/extension_ai_polished/orm-repro/.venv/lib/python3.13/site-packages/gel/_internal/_qbmodel/_abstract/_descriptors.py", line 89, in _try_resolve_type
    raise AssertionError(
        f"{self._fqname} type argument is not a GelType: {t}"
    )
AssertionError: models.__variants__.cfg.ExtensionConfig.__variants__.Partial.cfg type argument is not a GelType: models.cfg.AbstractConfig | models.__variants__.cfg.AbstractConfig.__variants__.Partial
```

**Comment by anbuzin** [comment]
> Maybe uv is caching the package for you and you didn't get a fresh build of master?

I checked the lock file though, says 

```
[[package]]
name = "gel"
version = "3.1.0"
source = { git = "https://github.com/geldata/gel-python.git#60800748801dd5ebac89a185785a6f99578a99e5" }
dependencies = [
    { name = "certifi", marker = "sys_platform == 'win32'" },
    { name = "pydantic" },
    { name = "typing-extensions" },
    { name = "typing-inspection" },
]
```

(I've tried with the latest master + 6.7, the error still persists)

**Comment by anbuzin** [comment]
Yeah I can't seem to reproduce that error in a new project, the new one gives the new error regardless of the Gel version. The old one still gives the old error. I don't know what that's about, maybe something got cached somewhere after a bunch of migrations.

**Comment by anbuzin** [comment]
I'm still getting the same error in a brand new project, double checked the lock file

```toml
[[package]]
name = "gel"
version = "3.1.0"
source = { git = "https://github.com/geldata/gel-python.git#ff1cf42315c42319304073505727861c8820872d" }
dependencies = [
    { name = "certifi", marker = "sys_platform == 'win32'" },
    { name = "pydantic" },
    { name = "typing-extensions" },
    { name = "typing-inspection" },
]
```

At this point I'm questioning if I'm holding it wrong...
